version: "3.9"

services:

  bootnode:
    image: "hawyasunaga/ethereum-bootnode:latest"
    command: bootnode -nodekey /bootnode/boot.key -verbosity 5
    container_name: bootnode
    volumes:
      - ./bootnode:/bootnode
    ports:
      - "30301:30301/tcp"
      - "30301:30301/udp"