version: "3.9"

services:

  init_root: # init root
    image: ethereum/client-go:latest
    container_name: init_root
    command: init --datadir root /root/genesis.json
    volumes:
      - ./root:/root
      - ./genesis.json:/root/genesis.json

  root:
    image: ethereum/client-go:latest
    container_name: root
    depends_on:
      init_root:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - --networkid=12345
      - --datadir=/root
      - --bootnodes=${ENODE}
      - --port=30309
      - --syncmode=full
      - --ipcdisable
      - --allow-insecure-unlock
      - --unlock=0xa29b97db3276978d3c8cbac72086b95b42a0b716
      - --password=/root/password.txt
      - --mine
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,personal,miner,txpool,admin,clique
      - --http.port=6868
      - --authrpc.port=8553
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=3334
      - --ws.api=eth,net,web3,personal,miner,txpool,admin,clique
      - --ws.origins="*"
    volumes:
      - ./root:/root
      - ./genesis.json:/root/genesis.json
    ports:
      - 6868:6868
      - 8553:8553
      - "30309:30309/tcp"
      - "30309:30309/udp"
      - 3334:3334

  init_node1: # init node1
    image: ethereum/client-go:latest
    container_name: init_node1
    command: init --datadir node1 /node1/genesis.json
    volumes:
      - ./node1:/node1
      - ./genesis.json:/node1/genesis.json

  node1:
    image: ethereum/client-go:latest
    container_name: node1
    depends_on:
      init_node1:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - --networkid=12345
      - --datadir=/node1
      - --bootnodes=${ENODE}
      - --port=30303
      - --syncmode=full
      - --ipcdisable
      - --allow-insecure-unlock
      - --unlock=0x69c9beb160498fe802fd9dc2afb29f397531fe9c
      - --password=/node1/password.txt
      - --mine
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,personal,miner,txpool,admin,clique
      - --http.port=8888
      - --authrpc.port=8552
      - --http.vhosts=*
    volumes:
      - ./node1:/node1
      - ./genesis.json:/node2/genesis.json
    ports:
      - 8888:8888
      - 8552:8552
      - "30303:30303/tcp"
      - "30303:30303/udp"

  init_node2: # init node2
    image: ethereum/client-go:latest
    container_name: init_node2
    command: init --datadir node2 /node2/genesis.json
    volumes:
      - ./node2:/node2
      - ./genesis.json:/node2/genesis.json

  node2:
    image: ethereum/client-go:latest
    container_name: node2
    depends_on:
      init_node2:
        condition: service_completed_successfully
    env_file:
      - .env
    command:
      - --networkid=12345
      - --datadir=/node2
      - --bootnodes=${ENODE}
      - --port=30306
      - --syncmode=full
      - --ipcdisable
      - --allow-insecure-unlock
      - --unlock=0xe8926d5e627d9365e0616458bb7f0a1b691f7da8
      - --password=/node2/password.txt
      - --mine
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,personal,miner,txpool,admin,clique
      - --http.port=9999
      - --authrpc.port=8551
      - --http.vhosts=*
    volumes:
      - ./node2:/node2
      - ./genesis.json:/node2/genesis.json
    ports:
      - 9999:9999
      - 8551:8551
      - "30306:30306/tcp"
      - "30306:30306/udp"
